/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import dao.EstatusDao;
import dao.TecnicoDao;
import dto.Diagnostico;
import dto.Prueba;
import dto.Reparacion;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class Tecnico extends javax.swing.JFrame {

    /**
     * Creates new form Tecnico
     */
    public Tecnico() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void cargarTablas() {
        cargarEstatusDiagnostico();
        cargarEstatusReparacion();
        cargarEstatusPruebas();
    }

    public static String folioTexto = "";

    public void cargarEstatusDiagnostico() {
        DefaultTableModel estado = new DefaultTableModel();

        EstatusDao estatus = new EstatusDao();
        List<Diagnostico> asig = estatus.equipoEnDiagnostico();

        estado.addColumn("Tecnico");
        estado.addColumn("Folio");
        estado.addColumn("T. Equipo");
        estado.addColumn("Marca");
        estado.addColumn("Falla");
        estado.addColumn("Inicio Diagnostico");
        this.tablaDiagnostico.setModel(estado);

        Object[] o = new Object[6];
        for (Diagnostico asignados : asig) {

            o[0] = asignados.getNombre();
            o[1] = asignados.getFolio();
            o[2] = asignados.getTipoEquipo();
            o[3] = asignados.getMarca();
            o[4] = asignados.getFalla();
            o[5] = asignados.getInicioDiagnostico();
            estado.addRow(o);
        }
        this.tablaDiagnostico.setModel(estado);
    }

    public void cargarEstatusReparacion() {
        DefaultTableModel estado = new DefaultTableModel();

        EstatusDao estatus = new EstatusDao();
        List<Reparacion> reparaciones = estatus.equipoEnReparacion();

        estado.addColumn("Tecnico");
        estado.addColumn("Folio");
        estado.addColumn("T. Equipo");
        estado.addColumn("Marca");
        estado.addColumn("Inicio Reparacion");
        estado.addColumn("Diagnostico");
        this.tablaReparacion.setModel(estado);

        Object[] o = new Object[6];
        for (Reparacion estatusReparaciones : reparaciones) {
            o[0] = estatusReparaciones.getNombre();
            o[1] = estatusReparaciones.getFolio();
            o[2] = estatusReparaciones.getTipoEquipo();
            o[3] = estatusReparaciones.getMarca();
            o[4] = estatusReparaciones.getInicioReparacion();
            o[5] = estatusReparaciones.getDiagnostico();
            estado.addRow(o);
        }
        this.tablaReparacion.setModel(estado);
    }

    public void cargarEstatusPruebas() {
        DefaultTableModel estado = new DefaultTableModel();

        EstatusDao estatus = new EstatusDao();
        List<Prueba> reparaciones = estatus.equipoEnPrueba();

        estado.addColumn("Tecnico");
        estado.addColumn("Folio");
        estado.addColumn("T. Equipo");
        estado.addColumn("Marca");
        estado.addColumn("Inicio Pruebas");
        estado.addColumn("Pruebas");
        this.tablaPruebas.setModel(estado);

        Object[] o = new Object[6];
        for (Prueba estatusReparaciones : reparaciones) {

            o[0] = estatusReparaciones.getNombre();
            o[1] = estatusReparaciones.getFolio();
            o[2] = estatusReparaciones.getTipoEquipo();
            o[3] = estatusReparaciones.getMarca();
            o[4] = estatusReparaciones.getInicioPruebas();
            o[5] = estatusReparaciones.getPuebas();
            estado.addRow(o);
        }
        this.tablaPruebas.setModel(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDiagnostico = new javax.swing.JTable();
        abrirDiagnostico = new javax.swing.JButton();
        actualiza1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaReparacion = new javax.swing.JTable();
        finalizarRepara = new javax.swing.JButton();
        actualiza2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPruebas = new javax.swing.JTable();
        finalizarPrue = new javax.swing.JButton();
        actualiza3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaDiagnostico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tecnico", "Folio", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDiagnostico);

        abrirDiagnostico.setText("Diagnostico");
        abrirDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirDiagnosticoActionPerformed(evt);
            }
        });

        actualiza1.setText("Actualizar");
        actualiza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiza1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(abrirDiagnostico))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(actualiza1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualiza1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(abrirDiagnostico)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Diagnostico", jPanel1);

        tablaReparacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaReparacion);

        finalizarRepara.setText("Finalizar Reparacion");
        finalizarRepara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarReparaActionPerformed(evt);
            }
        });

        actualiza2.setText("Actualizar");
        actualiza2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiza2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(finalizarRepara))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(actualiza2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualiza2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(finalizarRepara)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Reparacion", jPanel2);

        tablaPruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaPruebas);

        finalizarPrue.setText("Finalizar Pruebas");
        finalizarPrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarPrueActionPerformed(evt);
            }
        });

        actualiza3.setText("Actualizar");
        actualiza3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiza3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(finalizarPrue))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(actualiza3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualiza3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(finalizarPrue)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pruebas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirDiagnosticoActionPerformed

        int selecRow = tablaDiagnostico.getSelectedRow();
        int folioDiagnostico = (int) tablaDiagnostico.getValueAt(selecRow, 1);
        folioTexto = String.valueOf(folioDiagnostico);
        //JOptionPane.showMessageDialog(null, "El folio seleccionado es: " + folioTexto);
        System.out.println(folioTexto);

        DesDiagnostico diag = new DesDiagnostico();
        diag.setVisible(true);

    }//GEN-LAST:event_abrirDiagnosticoActionPerformed

    private void finalizarReparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarReparaActionPerformed

        int selecRow = tablaReparacion.getSelectedRow();
        int folioDiagnostico = (int) tablaReparacion.getValueAt(selecRow, 1);
        JOptionPane.showMessageDialog(this, "El folio seleccionado es: " + folioDiagnostico);
        System.out.println(folioDiagnostico);

        TecnicoDao tec = new TecnicoDao();
        tec.terminarReparacion(folioDiagnostico);
        
        cargarTablas();
    }//GEN-LAST:event_finalizarReparaActionPerformed

    private void actualiza3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiza3ActionPerformed
        cargarTablas();
    }//GEN-LAST:event_actualiza3ActionPerformed

    private void actualiza2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiza2ActionPerformed
        cargarTablas();
    }//GEN-LAST:event_actualiza2ActionPerformed

    private void actualiza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiza1ActionPerformed
        cargarTablas();
    }//GEN-LAST:event_actualiza1ActionPerformed

    private void finalizarPrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarPrueActionPerformed
        int selecRow = tablaPruebas.getSelectedRow();
        int folioDiagnostico = (int) tablaPruebas.getValueAt(selecRow, 1);
        JOptionPane.showMessageDialog(null, "El folio seleccionado es: " + folioDiagnostico);
        System.out.println(folioTexto);

        TecnicoDao tec = new TecnicoDao();
        tec.terminarPruebas(folioDiagnostico);
        
        cargarTablas();
    }//GEN-LAST:event_finalizarPrueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirDiagnostico;
    private javax.swing.JButton actualiza1;
    private javax.swing.JButton actualiza2;
    private javax.swing.JButton actualiza3;
    private javax.swing.JButton finalizarPrue;
    private javax.swing.JButton finalizarRepara;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaDiagnostico;
    private javax.swing.JTable tablaPruebas;
    private javax.swing.JTable tablaReparacion;
    // End of variables declaration//GEN-END:variables
}
